In [3]:
import pandas as pd
from glob import glob

In [5]:
file = "/home/iagonmic/data_science/dialogic_accounting_pibic/data/processed/amostra_final_classificada.xlsx"

In [8]:
df = pd.read_excel(file)

In [33]:
df[df['Comments per post'] <= 101]['Comments per post'].sum()

np.int64(79521)

In [29]:
df.describe(percentiles=[0.90])

,index,Date,"Reactions, Comments & Shares",Likes per post,Comments per post,Message-ID,Profile-ID
count,4468.000000,4468,4468.000000,4468.000000,4468.000000,4.468000e+03,4.468000e+03
mean,770.977171,2024-07-08 13:27:33.088182784,770.849373,722.905998,47.943375,1.804541e+16,1.507357e+09
min,0.000000,2024-01-01 10:00:50,0.000000,0.000000,0.000000,1.784244e+16,1.006712e+07
50%,627.500000,2024-07-08 19:49:27,279.000000,264.500000,14.000000,1.802771e+16,6.107390e+08
90%,1601.000000,2024-11-30 12:19:51,1497.300000,1353.900000,101.000000,1.826518e+16,5.053307e+09
max,3549.000000,2025-01-01 02:29:40,100070.000000,88883.000000,11187.000000,1.848516e+16,8.162994e+09
std,646.944543,NaN,2855.018780,2675.652083,226.918826,1.327006e+14,2.031010e+09

In [34]:
df = df[df['Comments per post'] <= 101]

In [37]:
df.describe()

,index,Date,"Reactions, Comments & Shares",Likes per post,Comments per post,Message-ID,Profile-ID
count,4024.000000,4024,4024.000000,4024.000000,4024.00000,4.024000e+03,4.024000e+03
mean,792.345427,2024-07-09 11:27:37.603876608,401.201541,381.439861,19.76168,1.804566e+16,1.520850e+09
min,0.000000,2024-01-01 10:00:50,0.000000,0.000000,0.00000,1.784244e+16,1.006712e+07
25%,303.750000,2024-04-10 11:31:30.750000128,114.000000,108.000000,4.00000,1.797676e+16,2.633793e+08
50%,654.500000,2024-07-11 12:14:37,243.500000,227.000000,11.00000,1.802818e+16,6.107390e+08
75%,1078.250000,2024-10-07 21:50:37.500000,479.000000,447.250000,28.00000,1.806842e+16,1.553516e+09
max,3549.000000,2025-01-01 02:29:40,14098.000000,14031.000000,101.00000,1.848516e+16,8.162994e+09
std,663.044707,NaN,571.446237,559.059475,22.04594,1.333372e+14,2.036376e+09

In [36]:
df.to_excel('/home/iagonmic/data_science/dialogic_accounting_pibic/data/processed/amostra_final_101_comentarios.xlsx', index=False)